---
# tasks file for install-role

- name: Add jenkins key
  apt_key:
    state: present
    url: "{{ jenkins_key }}"

- name: Add entry into repository
  apt_repository:
    filename: "{{ jenkins.name }}"
    repo: "{{ jenkins.url }}"

- name: Update repository and install jenkins and java
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - openjdk-11-jre-headless
    - jenkins
